//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WebApplication2.Postcode {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="LookupSoap", Namespace="http://www.yell4postcode.co.uk/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AddressResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FullAddressResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InterimResult))]
    public partial class Lookup : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ByPostCodewithCountyOperationCompleted;
        
        private System.Threading.SendOrPostCallback ByPostCodewithpremisesOperationCompleted;
        
        private System.Threading.SendOrPostCallback ByPostCodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddressByIDWithCountyOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddressBypostcodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddressByIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAddressOperationCompleted;
        
        private System.Threading.SendOrPostCallback FindAccountNoOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddressByStreetOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddressByPostcodeOrTownOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAddressWithCountyOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetFullAddressWithCountyOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddressSearchByTextOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Lookup() {
            this.Url = global::WebApplication2.Properties.Settings.Default.WebApplication2_uk_co_yell4postcode_lookup_Lookup;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ByPostCodewithCountyCompletedEventHandler ByPostCodewithCountyCompleted;
        
        /// <remarks/>
        public event ByPostCodewithpremisesCompletedEventHandler ByPostCodewithpremisesCompleted;
        
        /// <remarks/>
        public event ByPostCodeCompletedEventHandler ByPostCodeCompleted;
        
        /// <remarks/>
        public event AddressByIDWithCountyCompletedEventHandler AddressByIDWithCountyCompleted;
        
        /// <remarks/>
        public event AddressBypostcodeCompletedEventHandler AddressBypostcodeCompleted;
        
        /// <remarks/>
        public event AddressByIDCompletedEventHandler AddressByIDCompleted;
        
        /// <remarks/>
        public event GetAddressCompletedEventHandler GetAddressCompleted;
        
        /// <remarks/>
        public event FindAccountNoCompletedEventHandler FindAccountNoCompleted;
        
        /// <remarks/>
        public event AddressByStreetCompletedEventHandler AddressByStreetCompleted;
        
        /// <remarks/>
        public event AddressByPostcodeOrTownCompletedEventHandler AddressByPostcodeOrTownCompleted;
        
        /// <remarks/>
        public event GetAddressWithCountyCompletedEventHandler GetAddressWithCountyCompleted;
        
        /// <remarks/>
        public event GetFullAddressWithCountyCompletedEventHandler GetFullAddressWithCountyCompleted;
        
        /// <remarks/>
        public event AddressSearchByTextCompletedEventHandler AddressSearchByTextCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.yell4postcode.co.uk/ByPostCodewithCounty", RequestNamespace="http://www.yell4postcode.co.uk/", ResponseNamespace="http://www.yell4postcode.co.uk/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public InterimResults ByPostCodewithCounty(string PostCode, string accountno, string CountyType, bool flgCounty) {
            object[] results = this.Invoke("ByPostCodewithCounty", new object[] {
                        PostCode,
                        accountno,
                        CountyType,
                        flgCounty});
            return ((InterimResults)(results[0]));
        }
        
        /// <remarks/>
        public void ByPostCodewithCountyAsync(string PostCode, string accountno, string CountyType, bool flgCounty) {
            this.ByPostCodewithCountyAsync(PostCode, accountno, CountyType, flgCounty, null);
        }
        
        /// <remarks/>
        public void ByPostCodewithCountyAsync(string PostCode, string accountno, string CountyType, bool flgCounty, object userState) {
            if ((this.ByPostCodewithCountyOperationCompleted == null)) {
                this.ByPostCodewithCountyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnByPostCodewithCountyOperationCompleted);
            }
            this.InvokeAsync("ByPostCodewithCounty", new object[] {
                        PostCode,
                        accountno,
                        CountyType,
                        flgCounty}, this.ByPostCodewithCountyOperationCompleted, userState);
        }
        
        private void OnByPostCodewithCountyOperationCompleted(object arg) {
            if ((this.ByPostCodewithCountyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ByPostCodewithCountyCompleted(this, new ByPostCodewithCountyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.yell4postcode.co.uk/ByPostCodewithpremises", RequestNamespace="http://www.yell4postcode.co.uk/", ResponseNamespace="http://www.yell4postcode.co.uk/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public InterimResults ByPostCodewithpremises(string PostCode, string accountno, string CountyType, bool flgCounty) {
            object[] results = this.Invoke("ByPostCodewithpremises", new object[] {
                        PostCode,
                        accountno,
                        CountyType,
                        flgCounty});
            return ((InterimResults)(results[0]));
        }
        
        /// <remarks/>
        public void ByPostCodewithpremisesAsync(string PostCode, string accountno, string CountyType, bool flgCounty) {
            this.ByPostCodewithpremisesAsync(PostCode, accountno, CountyType, flgCounty, null);
        }
        
        /// <remarks/>
        public void ByPostCodewithpremisesAsync(string PostCode, string accountno, string CountyType, bool flgCounty, object userState) {
            if ((this.ByPostCodewithpremisesOperationCompleted == null)) {
                this.ByPostCodewithpremisesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnByPostCodewithpremisesOperationCompleted);
            }
            this.InvokeAsync("ByPostCodewithpremises", new object[] {
                        PostCode,
                        accountno,
                        CountyType,
                        flgCounty}, this.ByPostCodewithpremisesOperationCompleted, userState);
        }
        
        private void OnByPostCodewithpremisesOperationCompleted(object arg) {
            if ((this.ByPostCodewithpremisesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ByPostCodewithpremisesCompleted(this, new ByPostCodewithpremisesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.yell4postcode.co.uk/ByPostCode", RequestNamespace="http://www.yell4postcode.co.uk/", ResponseNamespace="http://www.yell4postcode.co.uk/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public InterimResults ByPostCode(string PostCode, string accountno) {
            object[] results = this.Invoke("ByPostCode", new object[] {
                        PostCode,
                        accountno});
            return ((InterimResults)(results[0]));
        }
        
        /// <remarks/>
        public void ByPostCodeAsync(string PostCode, string accountno) {
            this.ByPostCodeAsync(PostCode, accountno, null);
        }
        
        /// <remarks/>
        public void ByPostCodeAsync(string PostCode, string accountno, object userState) {
            if ((this.ByPostCodeOperationCompleted == null)) {
                this.ByPostCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnByPostCodeOperationCompleted);
            }
            this.InvokeAsync("ByPostCode", new object[] {
                        PostCode,
                        accountno}, this.ByPostCodeOperationCompleted, userState);
        }
        
        private void OnByPostCodeOperationCompleted(object arg) {
            if ((this.ByPostCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ByPostCodeCompleted(this, new ByPostCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.yell4postcode.co.uk/AddressByIDWithCounty", RequestNamespace="http://www.yell4postcode.co.uk/", ResponseNamespace="http://www.yell4postcode.co.uk/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public AddressResults AddressByIDWithCounty(string ID, string CountyType, bool flgCounty) {
            object[] results = this.Invoke("AddressByIDWithCounty", new object[] {
                        ID,
                        CountyType,
                        flgCounty});
            return ((AddressResults)(results[0]));
        }
        
        /// <remarks/>
        public void AddressByIDWithCountyAsync(string ID, string CountyType, bool flgCounty) {
            this.AddressByIDWithCountyAsync(ID, CountyType, flgCounty, null);
        }
        
        /// <remarks/>
        public void AddressByIDWithCountyAsync(string ID, string CountyType, bool flgCounty, object userState) {
            if ((this.AddressByIDWithCountyOperationCompleted == null)) {
                this.AddressByIDWithCountyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddressByIDWithCountyOperationCompleted);
            }
            this.InvokeAsync("AddressByIDWithCounty", new object[] {
                        ID,
                        CountyType,
                        flgCounty}, this.AddressByIDWithCountyOperationCompleted, userState);
        }
        
        private void OnAddressByIDWithCountyOperationCompleted(object arg) {
            if ((this.AddressByIDWithCountyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddressByIDWithCountyCompleted(this, new AddressByIDWithCountyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.yell4postcode.co.uk/AddressBypostcode", RequestNamespace="http://www.yell4postcode.co.uk/", ResponseNamespace="http://www.yell4postcode.co.uk/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public AddressResults AddressBypostcode(string PostCode, string accountno, string CountyType, bool flgCounty) {
            object[] results = this.Invoke("AddressBypostcode", new object[] {
                        PostCode,
                        accountno,
                        CountyType,
                        flgCounty});
            return ((AddressResults)(results[0]));
        }
        
        /// <remarks/>
        public void AddressBypostcodeAsync(string PostCode, string accountno, string CountyType, bool flgCounty) {
            this.AddressBypostcodeAsync(PostCode, accountno, CountyType, flgCounty, null);
        }
        
        /// <remarks/>
        public void AddressBypostcodeAsync(string PostCode, string accountno, string CountyType, bool flgCounty, object userState) {
            if ((this.AddressBypostcodeOperationCompleted == null)) {
                this.AddressBypostcodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddressBypostcodeOperationCompleted);
            }
            this.InvokeAsync("AddressBypostcode", new object[] {
                        PostCode,
                        accountno,
                        CountyType,
                        flgCounty}, this.AddressBypostcodeOperationCompleted, userState);
        }
        
        private void OnAddressBypostcodeOperationCompleted(object arg) {
            if ((this.AddressBypostcodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddressBypostcodeCompleted(this, new AddressBypostcodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.yell4postcode.co.uk/AddressByID", RequestNamespace="http://www.yell4postcode.co.uk/", ResponseNamespace="http://www.yell4postcode.co.uk/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public AddressResults AddressByID(string ID) {
            object[] results = this.Invoke("AddressByID", new object[] {
                        ID});
            return ((AddressResults)(results[0]));
        }
        
        /// <remarks/>
        public void AddressByIDAsync(string ID) {
            this.AddressByIDAsync(ID, null);
        }
        
        /// <remarks/>
        public void AddressByIDAsync(string ID, object userState) {
            if ((this.AddressByIDOperationCompleted == null)) {
                this.AddressByIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddressByIDOperationCompleted);
            }
            this.InvokeAsync("AddressByID", new object[] {
                        ID}, this.AddressByIDOperationCompleted, userState);
        }
        
        private void OnAddressByIDOperationCompleted(object arg) {
            if ((this.AddressByIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddressByIDCompleted(this, new AddressByIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.yell4postcode.co.uk/GetAddress", RequestNamespace="http://www.yell4postcode.co.uk/", ResponseNamespace="http://www.yell4postcode.co.uk/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public FullAddressResults GetAddress(string PostCode, string accountno) {
            object[] results = this.Invoke("GetAddress", new object[] {
                        PostCode,
                        accountno});
            return ((FullAddressResults)(results[0]));
        }
        
        /// <remarks/>
        public void GetAddressAsync(string PostCode, string accountno) {
            this.GetAddressAsync(PostCode, accountno, null);
        }
        
        /// <remarks/>
        public void GetAddressAsync(string PostCode, string accountno, object userState) {
            if ((this.GetAddressOperationCompleted == null)) {
                this.GetAddressOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAddressOperationCompleted);
            }
            this.InvokeAsync("GetAddress", new object[] {
                        PostCode,
                        accountno}, this.GetAddressOperationCompleted, userState);
        }
        
        private void OnGetAddressOperationCompleted(object arg) {
            if ((this.GetAddressCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAddressCompleted(this, new GetAddressCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.yell4postcode.co.uk/FindAccountNo", RequestNamespace="http://www.yell4postcode.co.uk/", ResponseNamespace="http://www.yell4postcode.co.uk/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string FindAccountNo(string AccountNo) {
            object[] results = this.Invoke("FindAccountNo", new object[] {
                        AccountNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void FindAccountNoAsync(string AccountNo) {
            this.FindAccountNoAsync(AccountNo, null);
        }
        
        /// <remarks/>
        public void FindAccountNoAsync(string AccountNo, object userState) {
            if ((this.FindAccountNoOperationCompleted == null)) {
                this.FindAccountNoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFindAccountNoOperationCompleted);
            }
            this.InvokeAsync("FindAccountNo", new object[] {
                        AccountNo}, this.FindAccountNoOperationCompleted, userState);
        }
        
        private void OnFindAccountNoOperationCompleted(object arg) {
            if ((this.FindAccountNoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FindAccountNoCompleted(this, new FindAccountNoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.yell4postcode.co.uk/AddressByStreet", RequestNamespace="http://www.yell4postcode.co.uk/", ResponseNamespace="http://www.yell4postcode.co.uk/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public InterimResults AddressByStreet(string company, string building, string street, string posttown, string accountno) {
            object[] results = this.Invoke("AddressByStreet", new object[] {
                        company,
                        building,
                        street,
                        posttown,
                        accountno});
            return ((InterimResults)(results[0]));
        }
        
        /// <remarks/>
        public void AddressByStreetAsync(string company, string building, string street, string posttown, string accountno) {
            this.AddressByStreetAsync(company, building, street, posttown, accountno, null);
        }
        
        /// <remarks/>
        public void AddressByStreetAsync(string company, string building, string street, string posttown, string accountno, object userState) {
            if ((this.AddressByStreetOperationCompleted == null)) {
                this.AddressByStreetOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddressByStreetOperationCompleted);
            }
            this.InvokeAsync("AddressByStreet", new object[] {
                        company,
                        building,
                        street,
                        posttown,
                        accountno}, this.AddressByStreetOperationCompleted, userState);
        }
        
        private void OnAddressByStreetOperationCompleted(object arg) {
            if ((this.AddressByStreetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddressByStreetCompleted(this, new AddressByStreetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.yell4postcode.co.uk/AddressByPostcodeOrTown", RequestNamespace="http://www.yell4postcode.co.uk/", ResponseNamespace="http://www.yell4postcode.co.uk/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public InterimResults AddressByPostcodeOrTown(string TownOrPostCode, string accountno, string CountyType, bool flgCounty) {
            object[] results = this.Invoke("AddressByPostcodeOrTown", new object[] {
                        TownOrPostCode,
                        accountno,
                        CountyType,
                        flgCounty});
            return ((InterimResults)(results[0]));
        }
        
        /// <remarks/>
        public void AddressByPostcodeOrTownAsync(string TownOrPostCode, string accountno, string CountyType, bool flgCounty) {
            this.AddressByPostcodeOrTownAsync(TownOrPostCode, accountno, CountyType, flgCounty, null);
        }
        
        /// <remarks/>
        public void AddressByPostcodeOrTownAsync(string TownOrPostCode, string accountno, string CountyType, bool flgCounty, object userState) {
            if ((this.AddressByPostcodeOrTownOperationCompleted == null)) {
                this.AddressByPostcodeOrTownOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddressByPostcodeOrTownOperationCompleted);
            }
            this.InvokeAsync("AddressByPostcodeOrTown", new object[] {
                        TownOrPostCode,
                        accountno,
                        CountyType,
                        flgCounty}, this.AddressByPostcodeOrTownOperationCompleted, userState);
        }
        
        private void OnAddressByPostcodeOrTownOperationCompleted(object arg) {
            if ((this.AddressByPostcodeOrTownCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddressByPostcodeOrTownCompleted(this, new AddressByPostcodeOrTownCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.yell4postcode.co.uk/GetAddressWithCounty", RequestNamespace="http://www.yell4postcode.co.uk/", ResponseNamespace="http://www.yell4postcode.co.uk/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public FullAddressResults GetAddressWithCounty(string PostCode, string accountno, string CountyType, bool flgCounty) {
            object[] results = this.Invoke("GetAddressWithCounty", new object[] {
                        PostCode,
                        accountno,
                        CountyType,
                        flgCounty});
            return ((FullAddressResults)(results[0]));
        }
        
        /// <remarks/>
        public void GetAddressWithCountyAsync(string PostCode, string accountno, string CountyType, bool flgCounty) {
            this.GetAddressWithCountyAsync(PostCode, accountno, CountyType, flgCounty, null);
        }
        
        /// <remarks/>
        public void GetAddressWithCountyAsync(string PostCode, string accountno, string CountyType, bool flgCounty, object userState) {
            if ((this.GetAddressWithCountyOperationCompleted == null)) {
                this.GetAddressWithCountyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAddressWithCountyOperationCompleted);
            }
            this.InvokeAsync("GetAddressWithCounty", new object[] {
                        PostCode,
                        accountno,
                        CountyType,
                        flgCounty}, this.GetAddressWithCountyOperationCompleted, userState);
        }
        
        private void OnGetAddressWithCountyOperationCompleted(object arg) {
            if ((this.GetAddressWithCountyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAddressWithCountyCompleted(this, new GetAddressWithCountyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.yell4postcode.co.uk/GetFullAddressWithCounty", RequestNamespace="http://www.yell4postcode.co.uk/", ResponseNamespace="http://www.yell4postcode.co.uk/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public FullAddressResults GetFullAddressWithCounty(string PostCode, string accountno, string CountyType, bool flgCounty) {
            object[] results = this.Invoke("GetFullAddressWithCounty", new object[] {
                        PostCode,
                        accountno,
                        CountyType,
                        flgCounty});
            return ((FullAddressResults)(results[0]));
        }
        
        /// <remarks/>
        public void GetFullAddressWithCountyAsync(string PostCode, string accountno, string CountyType, bool flgCounty) {
            this.GetFullAddressWithCountyAsync(PostCode, accountno, CountyType, flgCounty, null);
        }
        
        /// <remarks/>
        public void GetFullAddressWithCountyAsync(string PostCode, string accountno, string CountyType, bool flgCounty, object userState) {
            if ((this.GetFullAddressWithCountyOperationCompleted == null)) {
                this.GetFullAddressWithCountyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFullAddressWithCountyOperationCompleted);
            }
            this.InvokeAsync("GetFullAddressWithCounty", new object[] {
                        PostCode,
                        accountno,
                        CountyType,
                        flgCounty}, this.GetFullAddressWithCountyOperationCompleted, userState);
        }
        
        private void OnGetFullAddressWithCountyOperationCompleted(object arg) {
            if ((this.GetFullAddressWithCountyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFullAddressWithCountyCompleted(this, new GetFullAddressWithCountyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.yell4postcode.co.uk/AddressSearchByText", RequestNamespace="http://www.yell4postcode.co.uk/", ResponseNamespace="http://www.yell4postcode.co.uk/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public InterimResults AddressSearchByText(string orgname, string outcome, string incode, string accountno) {
            object[] results = this.Invoke("AddressSearchByText", new object[] {
                        orgname,
                        outcome,
                        incode,
                        accountno});
            return ((InterimResults)(results[0]));
        }
        
        /// <remarks/>
        public void AddressSearchByTextAsync(string orgname, string outcome, string incode, string accountno) {
            this.AddressSearchByTextAsync(orgname, outcome, incode, accountno, null);
        }
        
        /// <remarks/>
        public void AddressSearchByTextAsync(string orgname, string outcome, string incode, string accountno, object userState) {
            if ((this.AddressSearchByTextOperationCompleted == null)) {
                this.AddressSearchByTextOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddressSearchByTextOperationCompleted);
            }
            this.InvokeAsync("AddressSearchByText", new object[] {
                        orgname,
                        outcome,
                        incode,
                        accountno}, this.AddressSearchByTextOperationCompleted, userState);
        }
        
        private void OnAddressSearchByTextOperationCompleted(object arg) {
            if ((this.AddressSearchByTextCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddressSearchByTextCompleted(this, new AddressSearchByTextCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.yell4postcode.co.uk/")]
    public partial class InterimResults {
        
        private object[] resultsField;
        
        /// <remarks/>
        public object[] Results {
            get {
                return this.resultsField;
            }
            set {
                this.resultsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.yell4postcode.co.uk/")]
    public partial class AddressResult {
        
        private string errorMessageField;
        
        private string organisationNameField;
        
        private string buildingNumberField;
        
        private string subbuildingNameField;
        
        private string buildingNameField;
        
        private string thoroughfareNameField;
        
        private string thoroughfareDescriptorField;
        
        private string dependentLocalityField;
        
        private string posttownField;
        
        private string countyField;
        
        private string outcomeField;
        
        private string incodeField;
        
        private string idField;
        
        /// <remarks/>
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        public string OrganisationName {
            get {
                return this.organisationNameField;
            }
            set {
                this.organisationNameField = value;
            }
        }
        
        /// <remarks/>
        public string BuildingNumber {
            get {
                return this.buildingNumberField;
            }
            set {
                this.buildingNumberField = value;
            }
        }
        
        /// <remarks/>
        public string SubbuildingName {
            get {
                return this.subbuildingNameField;
            }
            set {
                this.subbuildingNameField = value;
            }
        }
        
        /// <remarks/>
        public string BuildingName {
            get {
                return this.buildingNameField;
            }
            set {
                this.buildingNameField = value;
            }
        }
        
        /// <remarks/>
        public string ThoroughfareName {
            get {
                return this.thoroughfareNameField;
            }
            set {
                this.thoroughfareNameField = value;
            }
        }
        
        /// <remarks/>
        public string ThoroughfareDescriptor {
            get {
                return this.thoroughfareDescriptorField;
            }
            set {
                this.thoroughfareDescriptorField = value;
            }
        }
        
        /// <remarks/>
        public string DependentLocality {
            get {
                return this.dependentLocalityField;
            }
            set {
                this.dependentLocalityField = value;
            }
        }
        
        /// <remarks/>
        public string Posttown {
            get {
                return this.posttownField;
            }
            set {
                this.posttownField = value;
            }
        }
        
        /// <remarks/>
        public string County {
            get {
                return this.countyField;
            }
            set {
                this.countyField = value;
            }
        }
        
        /// <remarks/>
        public string Outcome {
            get {
                return this.outcomeField;
            }
            set {
                this.outcomeField = value;
            }
        }
        
        /// <remarks/>
        public string Incode {
            get {
                return this.incodeField;
            }
            set {
                this.incodeField = value;
            }
        }
        
        /// <remarks/>
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.yell4postcode.co.uk/")]
    public partial class FullAddressResult {
        
        private string fullAddressField;
        
        private string errorMessageField;
        
        private string dependentLocalityField;
        
        private string posttownField;
        
        private string countyField;
        
        private string outcomeField;
        
        private string incodeField;
        
        /// <remarks/>
        public string FullAddress {
            get {
                return this.fullAddressField;
            }
            set {
                this.fullAddressField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        public string DependentLocality {
            get {
                return this.dependentLocalityField;
            }
            set {
                this.dependentLocalityField = value;
            }
        }
        
        /// <remarks/>
        public string Posttown {
            get {
                return this.posttownField;
            }
            set {
                this.posttownField = value;
            }
        }
        
        /// <remarks/>
        public string County {
            get {
                return this.countyField;
            }
            set {
                this.countyField = value;
            }
        }
        
        /// <remarks/>
        public string Outcome {
            get {
                return this.outcomeField;
            }
            set {
                this.outcomeField = value;
            }
        }
        
        /// <remarks/>
        public string Incode {
            get {
                return this.incodeField;
            }
            set {
                this.incodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.yell4postcode.co.uk/")]
    public partial class FullAddressResults {
        
        private object[] resultsField;
        
        /// <remarks/>
        public object[] Results {
            get {
                return this.resultsField;
            }
            set {
                this.resultsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.yell4postcode.co.uk/")]
    public partial class AddressResults {
        
        private object[] resultsField;
        
        /// <remarks/>
        public object[] Results {
            get {
                return this.resultsField;
            }
            set {
                this.resultsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.yell4postcode.co.uk/")]
    public partial class InterimResult {
        
        private string errorMessageField;
        
        private string idField;
        
        private string descriptionField;
        
        private string description1Field;
        
        /// <remarks/>
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Description1 {
            get {
                return this.description1Field;
            }
            set {
                this.description1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void ByPostCodewithCountyCompletedEventHandler(object sender, ByPostCodewithCountyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ByPostCodewithCountyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ByPostCodewithCountyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public InterimResults Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((InterimResults)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void ByPostCodewithpremisesCompletedEventHandler(object sender, ByPostCodewithpremisesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ByPostCodewithpremisesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ByPostCodewithpremisesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public InterimResults Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((InterimResults)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void ByPostCodeCompletedEventHandler(object sender, ByPostCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ByPostCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ByPostCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public InterimResults Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((InterimResults)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void AddressByIDWithCountyCompletedEventHandler(object sender, AddressByIDWithCountyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddressByIDWithCountyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddressByIDWithCountyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AddressResults Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AddressResults)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void AddressBypostcodeCompletedEventHandler(object sender, AddressBypostcodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddressBypostcodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddressBypostcodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AddressResults Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AddressResults)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void AddressByIDCompletedEventHandler(object sender, AddressByIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddressByIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddressByIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AddressResults Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AddressResults)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetAddressCompletedEventHandler(object sender, GetAddressCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAddressCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAddressCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FullAddressResults Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FullAddressResults)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void FindAccountNoCompletedEventHandler(object sender, FindAccountNoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FindAccountNoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FindAccountNoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void AddressByStreetCompletedEventHandler(object sender, AddressByStreetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddressByStreetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddressByStreetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public InterimResults Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((InterimResults)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void AddressByPostcodeOrTownCompletedEventHandler(object sender, AddressByPostcodeOrTownCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddressByPostcodeOrTownCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddressByPostcodeOrTownCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public InterimResults Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((InterimResults)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetAddressWithCountyCompletedEventHandler(object sender, GetAddressWithCountyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAddressWithCountyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAddressWithCountyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FullAddressResults Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FullAddressResults)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetFullAddressWithCountyCompletedEventHandler(object sender, GetFullAddressWithCountyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFullAddressWithCountyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFullAddressWithCountyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FullAddressResults Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FullAddressResults)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void AddressSearchByTextCompletedEventHandler(object sender, AddressSearchByTextCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddressSearchByTextCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddressSearchByTextCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public InterimResults Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((InterimResults)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591